import Nav from "./Nav";
import Button from "./Button";
import  DetailsScroll  from "./DetailsScroll";
import Loader from "./Loader";
import TextGenerateEffect from "./TextGenerateEffect";
import ScrollToTop from "./ScrollToTop";
import Collapsible from "./Collapsible";
import  Compare  from "./Compare";
import useGoogleAnalytics from "./useGoogleAnalytics";
import Video_Comparison from "./Video_Comparison";
export { Nav, Button, DetailsScroll, Loader, TextGenerateEffect, ScrollToTop , Collapsible, Compare, useGoogleAnalytics, Video_Comparison };